language: cpp

# do not test on ubuntu 12.04, using 14.04
dist: trusty

python:
  - "2.7" # this is the officially tested and supported one for now
  - "2.6"
  - "3.2"
  - "3.3"

matrix:
  allow_failures:
    # not tested at all yet:
    - python: 2.6
    - python: 3.2
    - python: 3.3

compiler:
  - clang
# No GCC atm because gcc 4.6 doesn't know about "--std=c++11" and I dont want
# to have extra handling just for GCC.

# Travis' Boost is too old (1.46 I think; it misses boost/atomic.hpp).
# We need at least >=1.55. smart_ptr/intrusive_ref_counter.hpp doesn't exist in older ones.
# Thus, install a newer one:
before_install:
 - wget http://sourceforge.net/projects/boost/files/boost/1.55.0/boost_1_55_0.tar.bz2
 - tar --bzip2 -xf boost_1_55_0.tar.bz2
 - cd boost_1_55_0
 - ./bootstrap.sh --help
# We only need atomic (and also only header-only).
# All the rest takes way too much time to compile.
 - sudo ./bootstrap.sh --with-libraries="atomic"
# Way too much output, so just display the last 50 lines.
 - sudo ./b2 install | tail -n 50
 - cd ..

env:
  CFLAGS=-I/usr/local/include

install:
  - sudo apt-get -qq update
  - sudo apt-get install -y python-dev libsnappy-dev libtool
  - sudo apt-get install -y yasm libchromaprint-dev portaudio19-dev libboost-dev
  - sudo apt-get install -y libavformat-dev libswresample-dev
#  - sudo add-apt-repository -y ppa:mc3man/trusty-media
#  - sudo apt-get install -y ffmpeg

script:
  - python setup.py build
  - sudo python setup.py install
  - python -c "import musicplayer as mp; p = mp.createPlayer()"
